Exceptions (pyobs.utils.exceptions)
-----------------------------------

.. automodule:: pyobs.utils.exceptions

ExceptionHandler
~~~~~~~~~~~~~~~~

.. autoclass:: pyobs.utils.exceptions.ExceptionHandler
   :members:
   :undoc-members:

GrabImageError
~~~~~~~~~~~~~~

.. autoclass:: pyobs.utils.exceptions.GrabImageError
   :members:
   :undoc-members:

InitError
~~~~~~~~~

.. autoclass:: pyobs.utils.exceptions.InitError
   :members:
   :undoc-members:

InvocationError
~~~~~~~~~~~~~~~

.. autoclass:: pyobs.utils.exceptions.InvocationError
   :members:
   :undoc-members:

LoggedException
~~~~~~~~~~~~~~~

.. autoclass:: pyobs.utils.exceptions.LoggedException
   :members:
   :undoc-members:

ModuleError
~~~~~~~~~~~

.. autoclass:: pyobs.utils.exceptions.ModuleError
   :members:
   :undoc-members:

MotionError
~~~~~~~~~~~

.. autoclass:: pyobs.utils.exceptions.MotionError
   :members:
   :undoc-members:

MoveError
~~~~~~~~~

.. autoclass:: pyobs.utils.exceptions.MoveError
   :members:
   :undoc-members:

ParkError
~~~~~~~~~

.. autoclass:: pyobs.utils.exceptions.ParkError
   :members:
   :undoc-members:

PyObsError
~~~~~~~~~~

.. autoclass:: pyobs.utils.exceptions.PyObsError
   :members:
   :undoc-members:

RemoteError
~~~~~~~~~~~

.. autoclass:: pyobs.utils.exceptions.RemoteError
   :members:
   :undoc-members:

RemoteTimeoutError
~~~~~~~~~~~~~~~~~~

.. autoclass:: pyobs.utils.exceptions.RemoteTimeoutError
   :members:
   :undoc-members:

SevereError
~~~~~~~~~~~

.. autoclass:: pyobs.utils.exceptions.SevereError
   :members:
   :undoc-members:

_Meta
~~~~~

.. autoclass:: pyobs.utils.exceptions._Meta
   :members:
   :undoc-members:

